# Generated by Django 5.0.3 on 2024-07-09 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_client_owner_message_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank='True', null='True', verbose_name='Описание')),
                ('status', models.CharField(choices=[('Завершена', 'Завершена'), ('Создана', 'Создана'), ('Запущена', 'Запущена')], default='Создана', max_length=150, verbose_name='Статус')),
                ('periodicity', models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Раз в день', max_length=150, verbose_name='Периодичность')),
                ('start_date', models.DateTimeField(blank='True', null='True', verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank='True', help_text='не обязательное поле', null='True', verbose_name='Дата окончания')),
                ('next_send_time', models.DateTimeField(blank='True', null='True', verbose_name='Время следующей отправки')),
                ('clients', models.ManyToManyField(related_name='mailing', to='mailing.client', verbose_name='Клиенты рассылки')),
                ('message', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Cообщение')),
                ('owner', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
