# Generated by Django 5.0.3 on 2024-07-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('name',), 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
