# Generated by Django 5.0.3 on 2024-07-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('name',), 'permissions': [('deactivate_mailing', 'Can deactivate mailing'), ('view_all_mailings', 'Can view all mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
